name: CI/CD

on:
  workflow_dispatch:  # Запуск кнопкой "Run workflow"
  push:               # Запуск при коммите
  pull_request:       # Запуск при PR
    branches:
      - main

permissions:
  contents: write     # Разрешение записи

jobs:
  build:
    runs-on: ubuntu-latest  # Выполняется на ВМ Ubuntu

    steps:
      - name: Клонирование кода репозитория на ВМ
        uses: actions/checkout@v4

      - name: Установка необходимых зависимостей
        run: sudo apt update && sudo apt install -y cmake g++

      - name: Создание файлов сборки
        run: cmake .

      - name: Сборка
        run: cmake --build .
      
      - name: Запуск тестов
        run: ./tests

      - name: Генерация документации
        run: doxygen Doxyfile

      - name: Индентиыикация
        if: github.event_name == 'push'
        run: |
          git config --global user.email "ishakinc@yandex.ru"
          git config --global user.name "asdwqerz"
          
      - name: Коммит изменений документации
        if: github.event_name == 'push'
        run: |
          git add docs/
          git commit -m "Автоматичесткое обновление документации"
          git push 